# Generated by Django 2.1.2 on 2019-03-18 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('surname', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=200, verbose_name='Отчетсво')),
                ('Birthdate', models.DateField(verbose_name='Дата рождения')),
                ('telefon', models.CharField(max_length=200, verbose_name='телефон')),
                ('pasport', models.CharField(max_length=200, verbose_name='паспорт')),
                ('ball', models.IntegerField(verbose_name='скоринговый балл')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('sent', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('status', models.CharField(blank=True, choices=[('n', 'новая'), ('o', 'отправлена'), ('p', 'получена'), ('e', 'одобрено'), ('t', 'отказано'), ('d', 'выдано')], default='n', help_text='Статус', max_length=1)),
                ('anketa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa.Anketa', verbose_name='Анкета')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('start_rotation', models.DateTimeField(blank=True, null=True, verbose_name='Начало ротации')),
                ('stop_rotation', models.DateTimeField(blank=True, null=True, verbose_name='Конец ротации')),
                ('min_ball', models.IntegerField(verbose_name='минимальный скоринговый балл')),
                ('max_ball', models.IntegerField(verbose_name='максимальный скоринговый балл')),
                ('status', models.CharField(blank=True, choices=[('p', 'потреб'), ('i', 'ипотека'), ('a', 'автокредит')], default='p', help_text='Статус', max_length=1)),
            ],
            options={
                'verbose_name': 'Предложение',
                'verbose_name_plural': 'Предложения',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='credit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa.Organization', verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='bid',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa.Offer', verbose_name='Предложение'),
        ),
        migrations.AddField(
            model_name='anketa',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anketa.Partner', verbose_name='Партнер'),
        ),
    ]
