# Generated by Django 2.1.2 on 2019-03-20 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='customer',
            field=models.ManyToManyField(related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
